# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Aug 30 02:56:47 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(691, 534)
        MainWindow.setWindowTitle("PyHomeLib")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pyhomelib.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(320, 200))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtGui.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 29))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.authorEdit = QtGui.QLineEdit(self.widget)
        self.authorEdit.setObjectName("authorEdit")
        self.horizontalLayout_3.addWidget(self.authorEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.authorsView = TableView(self.widget)
        self.authorsView.setObjectName("authorsView")
        self.authorsView.horizontalHeader().setVisible(False)
        self.authorsView.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.authorsView)
        self.tabWidget.addTab(self.widget, "")
        self.widget_2 = QtGui.QWidget()
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 29))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.sequenceEdit = QtGui.QLineEdit(self.widget_2)
        self.sequenceEdit.setObjectName("sequenceEdit")
        self.horizontalLayout_4.addWidget(self.sequenceEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.sequencesView = TableView(self.widget_2)
        self.sequencesView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sequencesView.setGridStyle(QtCore.Qt.SolidLine)
        self.sequencesView.setSortingEnabled(True)
        self.sequencesView.setObjectName("sequencesView")
        self.sequencesView.horizontalHeader().setVisible(False)
        self.sequencesView.horizontalHeader().setStretchLastSection(True)
        self.sequencesView.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.sequencesView)
        self.tabWidget.addTab(self.widget_2, "")
        self.widget_3 = QtGui.QWidget()
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.genresTree = TreeView(self.widget_3)
        self.genresTree.setHeaderHidden(True)
        self.genresTree.setObjectName("genresTree")
        self.verticalLayout_2.addWidget(self.genresTree)
        self.tabWidget.addTab(self.widget_3, "")
        self.widget_4 = QtGui.QWidget()
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.searchByAuthorEdit = QtGui.QLineEdit(self.widget_4)
        self.searchByAuthorEdit.setObjectName("searchByAuthorEdit")
        self.gridLayout.addWidget(self.searchByAuthorEdit, 0, 1, 1, 1)
        self.searchByTitleEdit = QtGui.QLineEdit(self.widget_4)
        self.searchByTitleEdit.setObjectName("searchByTitleEdit")
        self.gridLayout.addWidget(self.searchByTitleEdit, 2, 1, 1, 1)
        self.searchBySeqEdit = QtGui.QLineEdit(self.widget_4)
        self.searchBySeqEdit.setObjectName("searchBySeqEdit")
        self.gridLayout.addWidget(self.searchBySeqEdit, 4, 1, 1, 1)
        self.searchByGenreEdit = QtGui.QLineEdit(self.widget_4)
        self.searchByGenreEdit.setObjectName("searchByGenreEdit")
        self.gridLayout.addWidget(self.searchByGenreEdit, 6, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.searchByFileAuthorEdit = QtGui.QLineEdit(self.widget_4)
        self.searchByFileAuthorEdit.setObjectName("searchByFileAuthorEdit")
        self.gridLayout.addWidget(self.searchByFileAuthorEdit, 8, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 7, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)
        self.searchByMd5Edit = QtGui.QLineEdit(self.widget_4)
        self.searchByMd5Edit.setObjectName("searchByMd5Edit")
        self.gridLayout.addWidget(self.searchByMd5Edit, 10, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 9, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.tabWidget.addTab(self.widget_4, "")
        self.widget_5 = QtGui.QWidget()
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtGui.QLabel(self.widget_5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.groupEdit = QtGui.QLineEdit(self.widget_5)
        self.groupEdit.setObjectName("groupEdit")
        self.horizontalLayout_9.addWidget(self.groupEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.groupsView = TableView(self.widget_5)
        self.groupsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.groupsView.setObjectName("groupsView")
        self.groupsView.horizontalHeader().setVisible(False)
        self.groupsView.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.groupsView)
        self.tabWidget.addTab(self.widget_5, "")
        self.stackedWidget = QtGui.QStackedWidget(self.splitter)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.authorTitleLabel = QtGui.QLabel(self.page)
        self.authorTitleLabel.setObjectName("authorTitleLabel")
        self.horizontalLayout_6.addWidget(self.authorTitleLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.booksByAuthorView = TableView(self.page)
        self.booksByAuthorView.setObjectName("booksByAuthorView")
        self.booksByAuthorView.horizontalHeader().setDefaultSectionSize(200)
        self.booksByAuthorView.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.booksByAuthorView)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.seqTitleLabel = QtGui.QLabel(self.page_2)
        self.seqTitleLabel.setObjectName("seqTitleLabel")
        self.horizontalLayout_5.addWidget(self.seqTitleLabel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.booksBySeqView = TableView(self.page_2)
        self.booksBySeqView.setObjectName("booksBySeqView")
        self.booksBySeqView.horizontalHeader().setDefaultSectionSize(200)
        self.booksBySeqView.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.booksBySeqView)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtGui.QLabel(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.genreTitleLabel = QtGui.QLabel(self.page_3)
        self.genreTitleLabel.setObjectName("genreTitleLabel")
        self.horizontalLayout_7.addWidget(self.genreTitleLabel)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.booksByGenreView = TableView(self.page_3)
        self.booksByGenreView.setObjectName("booksByGenreView")
        self.booksByGenreView.horizontalHeader().setDefaultSectionSize(200)
        self.booksByGenreView.verticalHeader().setVisible(False)
        self.verticalLayout_8.addWidget(self.booksByGenreView)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.searchForWidget = QuickSearchWidget(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchForWidget.sizePolicy().hasHeightForWidth())
        self.searchForWidget.setSizePolicy(sizePolicy)
        self.searchForWidget.setObjectName("searchForWidget")
        self.verticalLayout_9.addWidget(self.searchForWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtGui.QLabel(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.resultsTitleLabel = QtGui.QLabel(self.page_4)
        self.resultsTitleLabel.setObjectName("resultsTitleLabel")
        self.horizontalLayout_2.addWidget(self.resultsTitleLabel)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.bookSearchView = TableView(self.page_4)
        self.bookSearchView.setObjectName("bookSearchView")
        self.bookSearchView.horizontalHeader().setVisible(True)
        self.bookSearchView.horizontalHeader().setDefaultSectionSize(200)
        self.bookSearchView.verticalHeader().setVisible(False)
        self.verticalLayout_9.addWidget(self.bookSearchView)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_13 = QtGui.QLabel(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.groupTitleLabel = QtGui.QLabel(self.page_5)
        self.groupTitleLabel.setObjectName("groupTitleLabel")
        self.horizontalLayout.addWidget(self.groupTitleLabel)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.booksByGroupView = TableView(self.page_5)
        self.booksByGroupView.setObjectName("booksByGroupView")
        self.booksByGroupView.horizontalHeader().setVisible(True)
        self.booksByGroupView.horizontalHeader().setDefaultSectionSize(200)
        self.booksByGroupView.verticalHeader().setVisible(False)
        self.verticalLayout_10.addWidget(self.booksByGroupView)
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout_11.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 691, 20))
        self.menuBar.setObjectName("menuBar")
        self.helpMenu = QtGui.QMenu(self.menuBar)
        self.helpMenu.setObjectName("helpMenu")
        self.databaseMenu = QtGui.QMenu(self.menuBar)
        self.databaseMenu.setObjectName("databaseMenu")
        self.viewMenu = QtGui.QMenu(self.menuBar)
        self.viewMenu.setObjectName("viewMenu")
        self.settingsMenu = QtGui.QMenu(self.menuBar)
        self.settingsMenu.setObjectName("settingsMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.ruLettersToolbar = QtGui.QToolBar(MainWindow)
        self.ruLettersToolbar.setObjectName("ruLettersToolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.ruLettersToolbar)
        self.enLettersToolbar = QtGui.QToolBar(MainWindow)
        self.enLettersToolbar.setObjectName("enLettersToolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.enLettersToolbar)
        MainWindow.insertToolBarBreak(self.enLettersToolbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(220, 119))
        self.dockWidget.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.coverpageLabel = QtGui.QLabel(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coverpageLabel.sizePolicy().hasHeightForWidth())
        self.coverpageLabel.setSizePolicy(sizePolicy)
        self.coverpageLabel.setMinimumSize(QtCore.QSize(200, 0))
        self.coverpageLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.coverpageLabel.setObjectName("coverpageLabel")
        self.verticalLayout_12.addWidget(self.coverpageLabel)
        self.annotationEdit = QtGui.QTextEdit(self.dockWidgetContents)
        self.annotationEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.annotationEdit.setMaximumSize(QtCore.QSize(200, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(235, 235, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 235, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 244, 244))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.annotationEdit.setPalette(palette)
        self.annotationEdit.setFrameShape(QtGui.QFrame.NoFrame)
        self.annotationEdit.setFrameShadow(QtGui.QFrame.Plain)
        self.annotationEdit.setReadOnly(True)
        self.annotationEdit.setObjectName("annotationEdit")
        self.verticalLayout_12.addWidget(self.annotationEdit)
        self.horizontalLayout_8.addLayout(self.verticalLayout_12)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionEnLetterA = QtGui.QAction(MainWindow)
        self.actionEnLetterA.setCheckable(True)
        self.actionEnLetterA.setText("A")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterA.setFont(font)
        self.actionEnLetterA.setObjectName("actionEnLetterA")
        self.actionEnLetterB = QtGui.QAction(MainWindow)
        self.actionEnLetterB.setCheckable(True)
        self.actionEnLetterB.setText("B")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterB.setFont(font)
        self.actionEnLetterB.setObjectName("actionEnLetterB")
        self.actionEnLetterC = QtGui.QAction(MainWindow)
        self.actionEnLetterC.setCheckable(True)
        self.actionEnLetterC.setText("C")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterC.setFont(font)
        self.actionEnLetterC.setObjectName("actionEnLetterC")
        self.actionEnLetterD = QtGui.QAction(MainWindow)
        self.actionEnLetterD.setCheckable(True)
        self.actionEnLetterD.setText("D")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterD.setFont(font)
        self.actionEnLetterD.setObjectName("actionEnLetterD")
        self.actionEnLetterE = QtGui.QAction(MainWindow)
        self.actionEnLetterE.setCheckable(True)
        self.actionEnLetterE.setText("E")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterE.setFont(font)
        self.actionEnLetterE.setObjectName("actionEnLetterE")
        self.actionEnLetterF = QtGui.QAction(MainWindow)
        self.actionEnLetterF.setCheckable(True)
        self.actionEnLetterF.setText("F")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterF.setFont(font)
        self.actionEnLetterF.setObjectName("actionEnLetterF")
        self.actionEnLetterG = QtGui.QAction(MainWindow)
        self.actionEnLetterG.setCheckable(True)
        self.actionEnLetterG.setText("G")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterG.setFont(font)
        self.actionEnLetterG.setObjectName("actionEnLetterG")
        self.actionEnLetterH = QtGui.QAction(MainWindow)
        self.actionEnLetterH.setCheckable(True)
        self.actionEnLetterH.setText("H")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterH.setFont(font)
        self.actionEnLetterH.setObjectName("actionEnLetterH")
        self.actionEnLetterI = QtGui.QAction(MainWindow)
        self.actionEnLetterI.setCheckable(True)
        self.actionEnLetterI.setText("I")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterI.setFont(font)
        self.actionEnLetterI.setObjectName("actionEnLetterI")
        self.actionEnLetterJ = QtGui.QAction(MainWindow)
        self.actionEnLetterJ.setCheckable(True)
        self.actionEnLetterJ.setText("J")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterJ.setFont(font)
        self.actionEnLetterJ.setObjectName("actionEnLetterJ")
        self.actionEnLetterK = QtGui.QAction(MainWindow)
        self.actionEnLetterK.setCheckable(True)
        self.actionEnLetterK.setText("K")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterK.setFont(font)
        self.actionEnLetterK.setObjectName("actionEnLetterK")
        self.actionEnLetterL = QtGui.QAction(MainWindow)
        self.actionEnLetterL.setCheckable(True)
        self.actionEnLetterL.setText("L")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterL.setFont(font)
        self.actionEnLetterL.setObjectName("actionEnLetterL")
        self.actionEnLetterM = QtGui.QAction(MainWindow)
        self.actionEnLetterM.setCheckable(True)
        self.actionEnLetterM.setText("M")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterM.setFont(font)
        self.actionEnLetterM.setObjectName("actionEnLetterM")
        self.actionEnLetterN = QtGui.QAction(MainWindow)
        self.actionEnLetterN.setCheckable(True)
        self.actionEnLetterN.setText("N")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterN.setFont(font)
        self.actionEnLetterN.setObjectName("actionEnLetterN")
        self.actionEnLetterO = QtGui.QAction(MainWindow)
        self.actionEnLetterO.setCheckable(True)
        self.actionEnLetterO.setText("O")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterO.setFont(font)
        self.actionEnLetterO.setObjectName("actionEnLetterO")
        self.actionEnLetterP = QtGui.QAction(MainWindow)
        self.actionEnLetterP.setCheckable(True)
        self.actionEnLetterP.setText("P")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterP.setFont(font)
        self.actionEnLetterP.setObjectName("actionEnLetterP")
        self.actionEnLetterQ = QtGui.QAction(MainWindow)
        self.actionEnLetterQ.setCheckable(True)
        self.actionEnLetterQ.setText("Q")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterQ.setFont(font)
        self.actionEnLetterQ.setObjectName("actionEnLetterQ")
        self.actionEnLetterR = QtGui.QAction(MainWindow)
        self.actionEnLetterR.setCheckable(True)
        self.actionEnLetterR.setText("R")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterR.setFont(font)
        self.actionEnLetterR.setObjectName("actionEnLetterR")
        self.actionEnLetterS = QtGui.QAction(MainWindow)
        self.actionEnLetterS.setCheckable(True)
        self.actionEnLetterS.setText("S")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterS.setFont(font)
        self.actionEnLetterS.setObjectName("actionEnLetterS")
        self.actionEnLetterT = QtGui.QAction(MainWindow)
        self.actionEnLetterT.setCheckable(True)
        self.actionEnLetterT.setText("T")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterT.setFont(font)
        self.actionEnLetterT.setObjectName("actionEnLetterT")
        self.actionEnLetterU = QtGui.QAction(MainWindow)
        self.actionEnLetterU.setCheckable(True)
        self.actionEnLetterU.setText("U")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterU.setFont(font)
        self.actionEnLetterU.setObjectName("actionEnLetterU")
        self.actionEnLetterV = QtGui.QAction(MainWindow)
        self.actionEnLetterV.setCheckable(True)
        self.actionEnLetterV.setText("V")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterV.setFont(font)
        self.actionEnLetterV.setObjectName("actionEnLetterV")
        self.actionEnLetterW = QtGui.QAction(MainWindow)
        self.actionEnLetterW.setCheckable(True)
        self.actionEnLetterW.setText("W")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterW.setFont(font)
        self.actionEnLetterW.setObjectName("actionEnLetterW")
        self.actionEnLetterX = QtGui.QAction(MainWindow)
        self.actionEnLetterX.setCheckable(True)
        self.actionEnLetterX.setText("X")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterX.setFont(font)
        self.actionEnLetterX.setObjectName("actionEnLetterX")
        self.actionEnLetterY = QtGui.QAction(MainWindow)
        self.actionEnLetterY.setCheckable(True)
        self.actionEnLetterY.setText("Y")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterY.setFont(font)
        self.actionEnLetterY.setObjectName("actionEnLetterY")
        self.actionEnLetterZ = QtGui.QAction(MainWindow)
        self.actionEnLetterZ.setCheckable(True)
        self.actionEnLetterZ.setText("Z")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterZ.setFont(font)
        self.actionEnLetterZ.setObjectName("actionEnLetterZ")
        self.actionEnLetterAll = QtGui.QAction(MainWindow)
        self.actionEnLetterAll.setCheckable(True)
        self.actionEnLetterAll.setText("*")
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.actionEnLetterAll.setFont(font)
        self.actionEnLetterAll.setObjectName("actionEnLetterAll")
        self.actionRuLetterA = QtGui.QAction(MainWindow)
        self.actionRuLetterA.setCheckable(True)
        self.actionRuLetterA.setChecked(True)
        self.actionRuLetterA.setText("А")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterA.setFont(font)
        self.actionRuLetterA.setObjectName("actionRuLetterA")
        self.actionRuLetterB = QtGui.QAction(MainWindow)
        self.actionRuLetterB.setCheckable(True)
        self.actionRuLetterB.setText("Б")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterB.setFont(font)
        self.actionRuLetterB.setObjectName("actionRuLetterB")
        self.actionRuLetterV = QtGui.QAction(MainWindow)
        self.actionRuLetterV.setCheckable(True)
        self.actionRuLetterV.setText("В")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterV.setFont(font)
        self.actionRuLetterV.setObjectName("actionRuLetterV")
        self.actionRuLetterG = QtGui.QAction(MainWindow)
        self.actionRuLetterG.setCheckable(True)
        self.actionRuLetterG.setText("Г")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterG.setFont(font)
        self.actionRuLetterG.setObjectName("actionRuLetterG")
        self.actionRuLetterD = QtGui.QAction(MainWindow)
        self.actionRuLetterD.setCheckable(True)
        self.actionRuLetterD.setText("Д")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterD.setFont(font)
        self.actionRuLetterD.setObjectName("actionRuLetterD")
        self.actionRuLetterE = QtGui.QAction(MainWindow)
        self.actionRuLetterE.setCheckable(True)
        self.actionRuLetterE.setText("Е")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterE.setFont(font)
        self.actionRuLetterE.setObjectName("actionRuLetterE")
        self.actionRuLetterYo = QtGui.QAction(MainWindow)
        self.actionRuLetterYo.setCheckable(True)
        self.actionRuLetterYo.setText("Ё")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterYo.setFont(font)
        self.actionRuLetterYo.setObjectName("actionRuLetterYo")
        self.actionRuLetterZh = QtGui.QAction(MainWindow)
        self.actionRuLetterZh.setCheckable(True)
        self.actionRuLetterZh.setText("Ж")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterZh.setFont(font)
        self.actionRuLetterZh.setObjectName("actionRuLetterZh")
        self.actionRuLetterZ = QtGui.QAction(MainWindow)
        self.actionRuLetterZ.setCheckable(True)
        self.actionRuLetterZ.setText("З")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterZ.setFont(font)
        self.actionRuLetterZ.setObjectName("actionRuLetterZ")
        self.actionRuLetterI = QtGui.QAction(MainWindow)
        self.actionRuLetterI.setCheckable(True)
        self.actionRuLetterI.setText("И")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterI.setFont(font)
        self.actionRuLetterI.setObjectName("actionRuLetterI")
        self.actionRuLetterY = QtGui.QAction(MainWindow)
        self.actionRuLetterY.setCheckable(True)
        self.actionRuLetterY.setText("Й")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterY.setFont(font)
        self.actionRuLetterY.setObjectName("actionRuLetterY")
        self.actionRuLetterK = QtGui.QAction(MainWindow)
        self.actionRuLetterK.setCheckable(True)
        self.actionRuLetterK.setText("К")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterK.setFont(font)
        self.actionRuLetterK.setObjectName("actionRuLetterK")
        self.actionRuLetterL = QtGui.QAction(MainWindow)
        self.actionRuLetterL.setCheckable(True)
        self.actionRuLetterL.setText("Л")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterL.setFont(font)
        self.actionRuLetterL.setObjectName("actionRuLetterL")
        self.actionRuLetterM = QtGui.QAction(MainWindow)
        self.actionRuLetterM.setCheckable(True)
        self.actionRuLetterM.setText("М")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterM.setFont(font)
        self.actionRuLetterM.setObjectName("actionRuLetterM")
        self.actionRuLetterN = QtGui.QAction(MainWindow)
        self.actionRuLetterN.setCheckable(True)
        self.actionRuLetterN.setText("Н")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterN.setFont(font)
        self.actionRuLetterN.setObjectName("actionRuLetterN")
        self.actionRuLetterO = QtGui.QAction(MainWindow)
        self.actionRuLetterO.setCheckable(True)
        self.actionRuLetterO.setText("О")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterO.setFont(font)
        self.actionRuLetterO.setObjectName("actionRuLetterO")
        self.actionRuLetterP = QtGui.QAction(MainWindow)
        self.actionRuLetterP.setCheckable(True)
        self.actionRuLetterP.setText("П")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterP.setFont(font)
        self.actionRuLetterP.setObjectName("actionRuLetterP")
        self.actionRuLetterR = QtGui.QAction(MainWindow)
        self.actionRuLetterR.setCheckable(True)
        self.actionRuLetterR.setText("Р")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterR.setFont(font)
        self.actionRuLetterR.setObjectName("actionRuLetterR")
        self.actionRuLetterS = QtGui.QAction(MainWindow)
        self.actionRuLetterS.setCheckable(True)
        self.actionRuLetterS.setText("С")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterS.setFont(font)
        self.actionRuLetterS.setObjectName("actionRuLetterS")
        self.actionRuLetterT = QtGui.QAction(MainWindow)
        self.actionRuLetterT.setCheckable(True)
        self.actionRuLetterT.setText("Т")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterT.setFont(font)
        self.actionRuLetterT.setObjectName("actionRuLetterT")
        self.actionRuLetterU = QtGui.QAction(MainWindow)
        self.actionRuLetterU.setCheckable(True)
        self.actionRuLetterU.setText("У")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterU.setFont(font)
        self.actionRuLetterU.setObjectName("actionRuLetterU")
        self.actionRuLetterF = QtGui.QAction(MainWindow)
        self.actionRuLetterF.setCheckable(True)
        self.actionRuLetterF.setText("Ф")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterF.setFont(font)
        self.actionRuLetterF.setObjectName("actionRuLetterF")
        self.actionRuLetterH = QtGui.QAction(MainWindow)
        self.actionRuLetterH.setCheckable(True)
        self.actionRuLetterH.setText("Х")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterH.setFont(font)
        self.actionRuLetterH.setObjectName("actionRuLetterH")
        self.actionRuLetterTs = QtGui.QAction(MainWindow)
        self.actionRuLetterTs.setCheckable(True)
        self.actionRuLetterTs.setText("Ц")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterTs.setFont(font)
        self.actionRuLetterTs.setObjectName("actionRuLetterTs")
        self.actionRuLetterCh = QtGui.QAction(MainWindow)
        self.actionRuLetterCh.setCheckable(True)
        self.actionRuLetterCh.setText("Ч")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterCh.setFont(font)
        self.actionRuLetterCh.setObjectName("actionRuLetterCh")
        self.actionRuLetterSh = QtGui.QAction(MainWindow)
        self.actionRuLetterSh.setCheckable(True)
        self.actionRuLetterSh.setText("Ш")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterSh.setFont(font)
        self.actionRuLetterSh.setObjectName("actionRuLetterSh")
        self.actionRuLetterSch = QtGui.QAction(MainWindow)
        self.actionRuLetterSch.setCheckable(True)
        self.actionRuLetterSch.setText("Щ")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterSch.setFont(font)
        self.actionRuLetterSch.setObjectName("actionRuLetterSch")
        self.actionRuLetterYy = QtGui.QAction(MainWindow)
        self.actionRuLetterYy.setCheckable(True)
        self.actionRuLetterYy.setText("Ы")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterYy.setFont(font)
        self.actionRuLetterYy.setObjectName("actionRuLetterYy")
        self.actionRuLetterEe = QtGui.QAction(MainWindow)
        self.actionRuLetterEe.setCheckable(True)
        self.actionRuLetterEe.setText("Э")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterEe.setFont(font)
        self.actionRuLetterEe.setObjectName("actionRuLetterEe")
        self.actionRuLetterYu = QtGui.QAction(MainWindow)
        self.actionRuLetterYu.setCheckable(True)
        self.actionRuLetterYu.setText("Ю")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterYu.setFont(font)
        self.actionRuLetterYu.setObjectName("actionRuLetterYu")
        self.actionRuLetterYa = QtGui.QAction(MainWindow)
        self.actionRuLetterYa.setCheckable(True)
        self.actionRuLetterYa.setText("Я")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterYa.setFont(font)
        self.actionRuLetterYa.setObjectName("actionRuLetterYa")
        self.actionRuLetterAll = QtGui.QAction(MainWindow)
        self.actionRuLetterAll.setCheckable(True)
        self.actionRuLetterAll.setText("*")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionRuLetterAll.setFont(font)
        self.actionRuLetterAll.setObjectName("actionRuLetterAll")
        self.actionDbProperties = QtGui.QAction(MainWindow)
        self.actionDbProperties.setObjectName("actionDbProperties")
        self.actionDbScanBookDir = QtGui.QAction(MainWindow)
        self.actionDbScanBookDir.setObjectName("actionDbScanBookDir")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionViewBookInfo = QtGui.QAction(MainWindow)
        self.actionViewBookInfo.setCheckable(True)
        self.actionViewBookInfo.setChecked(True)
        self.actionViewBookInfo.setObjectName("actionViewBookInfo")
        self.actionRussianAlphabet = QtGui.QAction(MainWindow)
        self.actionRussianAlphabet.setCheckable(True)
        self.actionRussianAlphabet.setChecked(True)
        self.actionRussianAlphabet.setObjectName("actionRussianAlphabet")
        self.actionEnglishAlphabet = QtGui.QAction(MainWindow)
        self.actionEnglishAlphabet.setCheckable(True)
        self.actionEnglishAlphabet.setChecked(True)
        self.actionEnglishAlphabet.setObjectName("actionEnglishAlphabet")
        self.actionConfigure = QtGui.QAction(MainWindow)
        self.actionConfigure.setObjectName("actionConfigure")
        self.actionAboutQt = QtGui.QAction(MainWindow)
        self.actionAboutQt.setObjectName("actionAboutQt")
        self.actionStatistics = QtGui.QAction(MainWindow)
        self.actionStatistics.setObjectName("actionStatistics")
        self.helpMenu.addAction(self.actionAbout)
        self.helpMenu.addAction(self.actionAboutQt)
        self.databaseMenu.addAction(self.actionDbProperties)
        self.databaseMenu.addSeparator()
        self.databaseMenu.addAction(self.actionDbScanBookDir)
        self.databaseMenu.addSeparator()
        self.databaseMenu.addAction(self.actionStatistics)
        self.databaseMenu.addSeparator()
        self.databaseMenu.addAction(self.actionExit)
        self.viewMenu.addAction(self.actionViewBookInfo)
        self.viewMenu.addAction(self.actionRussianAlphabet)
        self.viewMenu.addAction(self.actionEnglishAlphabet)
        self.settingsMenu.addAction(self.actionConfigure)
        self.menuBar.addAction(self.databaseMenu.menuAction())
        self.menuBar.addAction(self.viewMenu.menuAction())
        self.menuBar.addAction(self.settingsMenu.menuAction())
        self.menuBar.addAction(self.helpMenu.menuAction())
        self.ruLettersToolbar.addAction(self.actionRuLetterAll)
        self.ruLettersToolbar.addAction(self.actionRuLetterA)
        self.ruLettersToolbar.addAction(self.actionRuLetterB)
        self.ruLettersToolbar.addAction(self.actionRuLetterV)
        self.ruLettersToolbar.addAction(self.actionRuLetterG)
        self.ruLettersToolbar.addAction(self.actionRuLetterD)
        self.ruLettersToolbar.addAction(self.actionRuLetterE)
        self.ruLettersToolbar.addAction(self.actionRuLetterYo)
        self.ruLettersToolbar.addAction(self.actionRuLetterZh)
        self.ruLettersToolbar.addAction(self.actionRuLetterZ)
        self.ruLettersToolbar.addAction(self.actionRuLetterI)
        self.ruLettersToolbar.addAction(self.actionRuLetterY)
        self.ruLettersToolbar.addAction(self.actionRuLetterK)
        self.ruLettersToolbar.addAction(self.actionRuLetterL)
        self.ruLettersToolbar.addAction(self.actionRuLetterM)
        self.ruLettersToolbar.addAction(self.actionRuLetterN)
        self.ruLettersToolbar.addAction(self.actionRuLetterO)
        self.ruLettersToolbar.addAction(self.actionRuLetterP)
        self.ruLettersToolbar.addAction(self.actionRuLetterR)
        self.ruLettersToolbar.addAction(self.actionRuLetterS)
        self.ruLettersToolbar.addAction(self.actionRuLetterT)
        self.ruLettersToolbar.addAction(self.actionRuLetterU)
        self.ruLettersToolbar.addAction(self.actionRuLetterF)
        self.ruLettersToolbar.addAction(self.actionRuLetterH)
        self.ruLettersToolbar.addAction(self.actionRuLetterTs)
        self.ruLettersToolbar.addAction(self.actionRuLetterCh)
        self.ruLettersToolbar.addAction(self.actionRuLetterSh)
        self.ruLettersToolbar.addAction(self.actionRuLetterSch)
        self.ruLettersToolbar.addAction(self.actionRuLetterYy)
        self.ruLettersToolbar.addAction(self.actionRuLetterEe)
        self.ruLettersToolbar.addAction(self.actionRuLetterYu)
        self.ruLettersToolbar.addAction(self.actionRuLetterYa)
        self.enLettersToolbar.addAction(self.actionEnLetterAll)
        self.enLettersToolbar.addAction(self.actionEnLetterA)
        self.enLettersToolbar.addAction(self.actionEnLetterB)
        self.enLettersToolbar.addAction(self.actionEnLetterC)
        self.enLettersToolbar.addAction(self.actionEnLetterD)
        self.enLettersToolbar.addAction(self.actionEnLetterE)
        self.enLettersToolbar.addAction(self.actionEnLetterF)
        self.enLettersToolbar.addAction(self.actionEnLetterG)
        self.enLettersToolbar.addAction(self.actionEnLetterH)
        self.enLettersToolbar.addAction(self.actionEnLetterI)
        self.enLettersToolbar.addAction(self.actionEnLetterJ)
        self.enLettersToolbar.addAction(self.actionEnLetterK)
        self.enLettersToolbar.addAction(self.actionEnLetterL)
        self.enLettersToolbar.addAction(self.actionEnLetterM)
        self.enLettersToolbar.addAction(self.actionEnLetterN)
        self.enLettersToolbar.addAction(self.actionEnLetterO)
        self.enLettersToolbar.addAction(self.actionEnLetterP)
        self.enLettersToolbar.addAction(self.actionEnLetterQ)
        self.enLettersToolbar.addAction(self.actionEnLetterR)
        self.enLettersToolbar.addAction(self.actionEnLetterS)
        self.enLettersToolbar.addAction(self.actionEnLetterT)
        self.enLettersToolbar.addAction(self.actionEnLetterU)
        self.enLettersToolbar.addAction(self.actionEnLetterV)
        self.enLettersToolbar.addAction(self.actionEnLetterW)
        self.enLettersToolbar.addAction(self.actionEnLetterX)
        self.enLettersToolbar.addAction(self.actionEnLetterY)
        self.enLettersToolbar.addAction(self.actionEnLetterZ)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.tabWidget, QtCore.SIGNAL("currentChanged(int)"), self.stackedWidget.setCurrentIndex)
        QtCore.QObject.connect(self.actionViewBookInfo, QtCore.SIGNAL("toggled(bool)"), self.dockWidget.setVisible)
        QtCore.QObject.connect(self.actionEnglishAlphabet, QtCore.SIGNAL("toggled(bool)"), self.enLettersToolbar.setVisible)
        QtCore.QObject.connect(self.actionRussianAlphabet, QtCore.SIGNAL("toggled(bool)"), self.ruLettersToolbar.setVisible)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Search:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), QtGui.QApplication.translate("MainWindow", "Authors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Search:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget_2), QtGui.QApplication.translate("MainWindow", "Sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget_3), QtGui.QApplication.translate("MainWindow", "Genres", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Genre:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Sequence:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Author:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "File author:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "MD5:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget_4), QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "New:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget_5), QtGui.QApplication.translate("MainWindow", "Groups", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Author:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Sequence:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Genre:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Search results:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Group:", None, QtGui.QApplication.UnicodeUTF8))
        self.helpMenu.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.databaseMenu.setTitle(QtGui.QApplication.translate("MainWindow", "&Database", None, QtGui.QApplication.UnicodeUTF8))
        self.viewMenu.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsMenu.setTitle(QtGui.QApplication.translate("MainWindow", "&Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.ruLettersToolbar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Russian alphabet", None, QtGui.QApplication.UnicodeUTF8))
        self.enLettersToolbar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "English alphabet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDbProperties.setText(QtGui.QApplication.translate("MainWindow", "&Properties...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDbScanBookDir.setText(QtGui.QApplication.translate("MainWindow", "&Add directory...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionViewBookInfo.setText(QtGui.QApplication.translate("MainWindow", "&Info panel", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRussianAlphabet.setText(QtGui.QApplication.translate("MainWindow", "&Russian alphabet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnglishAlphabet.setText(QtGui.QApplication.translate("MainWindow", "&English alphabet", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure.setText(QtGui.QApplication.translate("MainWindow", "&Configure...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAboutQt.setText(QtGui.QApplication.translate("MainWindow", "About Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStatistics.setText(QtGui.QApplication.translate("MainWindow", "&Statistics", None, QtGui.QApplication.UnicodeUTF8))

from treeview import TreeView
from quicksearchwidget import QuickSearchWidget
from tableview import TableView
import pyhomelib_rc
