# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsdialog.ui'
#
# Created: Thu Nov  5 15:18:19 2009
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(800, 600)
        self.horizontalLayout = QtGui.QHBoxLayout(SettingsDialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtGui.QListWidget(SettingsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.listWidget.setObjectName("listWidget")
        QtGui.QListWidgetItem(self.listWidget)
        QtGui.QListWidgetItem(self.listWidget)
        self.horizontalLayout.addWidget(self.listWidget)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtGui.QStackedWidget(SettingsDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtGui.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(183, 181, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(183, 181, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(183, 181, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.titleEdit1 = QtGui.QLineEdit(self.page)
        self.titleEdit1.setObjectName("titleEdit1")
        self.gridLayout.addWidget(self.titleEdit1, 1, 2, 1, 1)
        self.cmdEdit1 = QtGui.QLineEdit(self.page)
        self.cmdEdit1.setObjectName("cmdEdit1")
        self.gridLayout.addWidget(self.cmdEdit1, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setText("1")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 18, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setText("#")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setText("2")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setText("3")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setText("4")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setText("5")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setText("6")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 11, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setText("7")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 13, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setText("8")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 15, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setText("9")
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 17, 0, 1, 1)
        self.titleEdit2 = QtGui.QLineEdit(self.page)
        self.titleEdit2.setObjectName("titleEdit2")
        self.gridLayout.addWidget(self.titleEdit2, 3, 2, 1, 1)
        self.titleEdit3 = QtGui.QLineEdit(self.page)
        self.titleEdit3.setObjectName("titleEdit3")
        self.gridLayout.addWidget(self.titleEdit3, 5, 2, 1, 1)
        self.titleEdit4 = QtGui.QLineEdit(self.page)
        self.titleEdit4.setObjectName("titleEdit4")
        self.gridLayout.addWidget(self.titleEdit4, 7, 2, 1, 1)
        self.titleEdit5 = QtGui.QLineEdit(self.page)
        self.titleEdit5.setObjectName("titleEdit5")
        self.gridLayout.addWidget(self.titleEdit5, 9, 2, 1, 1)
        self.titleEdit6 = QtGui.QLineEdit(self.page)
        self.titleEdit6.setObjectName("titleEdit6")
        self.gridLayout.addWidget(self.titleEdit6, 11, 2, 1, 1)
        self.titleEdit7 = QtGui.QLineEdit(self.page)
        self.titleEdit7.setObjectName("titleEdit7")
        self.gridLayout.addWidget(self.titleEdit7, 13, 2, 1, 1)
        self.titleEdit8 = QtGui.QLineEdit(self.page)
        self.titleEdit8.setObjectName("titleEdit8")
        self.gridLayout.addWidget(self.titleEdit8, 15, 2, 1, 1)
        self.titleEdit9 = QtGui.QLineEdit(self.page)
        self.titleEdit9.setObjectName("titleEdit9")
        self.gridLayout.addWidget(self.titleEdit9, 17, 2, 1, 1)
        self.cmdEdit2 = QtGui.QLineEdit(self.page)
        self.cmdEdit2.setObjectName("cmdEdit2")
        self.gridLayout.addWidget(self.cmdEdit2, 3, 4, 1, 1)
        self.cmdEdit3 = QtGui.QLineEdit(self.page)
        self.cmdEdit3.setObjectName("cmdEdit3")
        self.gridLayout.addWidget(self.cmdEdit3, 5, 4, 1, 1)
        self.cmdEdit4 = QtGui.QLineEdit(self.page)
        self.cmdEdit4.setObjectName("cmdEdit4")
        self.gridLayout.addWidget(self.cmdEdit4, 7, 4, 1, 1)
        self.cmdEdit5 = QtGui.QLineEdit(self.page)
        self.cmdEdit5.setObjectName("cmdEdit5")
        self.gridLayout.addWidget(self.cmdEdit5, 9, 4, 1, 1)
        self.cmdEdit6 = QtGui.QLineEdit(self.page)
        self.cmdEdit6.setObjectName("cmdEdit6")
        self.gridLayout.addWidget(self.cmdEdit6, 11, 4, 1, 1)
        self.cmdEdit7 = QtGui.QLineEdit(self.page)
        self.cmdEdit7.setObjectName("cmdEdit7")
        self.gridLayout.addWidget(self.cmdEdit7, 13, 4, 1, 1)
        self.cmdEdit8 = QtGui.QLineEdit(self.page)
        self.cmdEdit8.setObjectName("cmdEdit8")
        self.gridLayout.addWidget(self.cmdEdit8, 15, 4, 1, 1)
        self.cmdEdit9 = QtGui.QLineEdit(self.page)
        self.cmdEdit9.setObjectName("cmdEdit9")
        self.gridLayout.addWidget(self.cmdEdit9, 17, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 4, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 6, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 8, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 14, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 12, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem8, 16, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem9, 10, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(183, 181, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(183, 181, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 145, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(183, 181, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.dontSaveUiOnExitBox = QtGui.QCheckBox(self.page_2)
        self.dontSaveUiOnExitBox.setObjectName("dontSaveUiOnExitBox")
        self.verticalLayout_2.addWidget(self.dontSaveUiOnExitBox)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.retranslateUi(SettingsDialog)
        self.listWidget.setCurrentRow(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.listWidget, QtCore.SIGNAL("currentRowChanged(int)"), self.stackedWidget.setCurrentIndex)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)
        SettingsDialog.setTabOrder(self.listWidget, self.titleEdit1)
        SettingsDialog.setTabOrder(self.titleEdit1, self.cmdEdit1)
        SettingsDialog.setTabOrder(self.cmdEdit1, self.titleEdit2)
        SettingsDialog.setTabOrder(self.titleEdit2, self.cmdEdit2)
        SettingsDialog.setTabOrder(self.cmdEdit2, self.titleEdit3)
        SettingsDialog.setTabOrder(self.titleEdit3, self.cmdEdit3)
        SettingsDialog.setTabOrder(self.cmdEdit3, self.titleEdit4)
        SettingsDialog.setTabOrder(self.titleEdit4, self.cmdEdit4)
        SettingsDialog.setTabOrder(self.cmdEdit4, self.titleEdit5)
        SettingsDialog.setTabOrder(self.titleEdit5, self.cmdEdit5)
        SettingsDialog.setTabOrder(self.cmdEdit5, self.titleEdit6)
        SettingsDialog.setTabOrder(self.titleEdit6, self.cmdEdit6)
        SettingsDialog.setTabOrder(self.cmdEdit6, self.titleEdit7)
        SettingsDialog.setTabOrder(self.titleEdit7, self.cmdEdit7)
        SettingsDialog.setTabOrder(self.cmdEdit7, self.titleEdit8)
        SettingsDialog.setTabOrder(self.titleEdit8, self.cmdEdit8)
        SettingsDialog.setTabOrder(self.cmdEdit8, self.titleEdit9)
        SettingsDialog.setTabOrder(self.titleEdit9, self.cmdEdit9)
        SettingsDialog.setTabOrder(self.cmdEdit9, self.buttonBox)
        SettingsDialog.setTabOrder(self.buttonBox, self.dontSaveUiOnExitBox)

    def retranslateUi(self, SettingsDialog):
        SettingsDialog.setWindowTitle(QtGui.QApplication.translate("SettingsDialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtGui.QApplication.translate("SettingsDialog", "Programs", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.item(1).setText(QtGui.QApplication.translate("SettingsDialog", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(QtGui.QApplication.translate("SettingsDialog", "Programs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SettingsDialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SettingsDialog", "Command line", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SettingsDialog", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.dontSaveUiOnExitBox.setText(QtGui.QApplication.translate("SettingsDialog", "Don\'t save UI settings on exit", None, QtGui.QApplication.UnicodeUTF8))

